name = "simplemoitor"
main = "src/index.ts"
compatibility_date = "2024-05-12"

[vars]
API_BASE = "https://api.telegram.org"
FEEDBACK_CHAT_ID = "5056710326"

# AUTH_USERNAME 和 AUTH_PASSWORD 已通过 secrets 设置
# wrangler secret put AUTH_USERNAME
# wrangler secret put AUTH_PASSWORD

# 使用 secrets 存储敏感信息：
# wrangler secret put BOT_TOKEN
# wrangler secret put FEEDBACK_BOT_TOKEN

[[d1_databases]]
binding = "DB"
database_name = "simplemoitor"
database_id = "c3374219-999a-416c-9cb2-46224d60c1f8"

[triggers]
crons = ["* * * * *"]
